### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by Laffery** [JdYwz/JdYwz.github.io#2]
1. release commens and replies
2. release blogs(main)

quickly

**Comment by JdYwz** [comment]
Hello, the comment system is already in use. Waiting for your comments.

**Comment by Laffery** [comment]
thx,ill hv a try



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JDywz"<notifications@github.com&gt;; 
发送时间: 2021年2月25日(星期四) 下午5:54
收件人: "JdYwz/JdYwz.github.io"<JdYwz.github.io@noreply.github.com&gt;; 
抄送: "🍊"<2387065420@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [JdYwz/JdYwz.github.io] requirements (#2)





 
Hello, the comment system is already in use. Waiting for your comments.

**Comment by Laffery** [comment]
A question that, will a reply to a comment be sent to his email, or other way to inform.
